version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
