name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      env:
        DOCKER_IMAGE: flask-app:latest
        DOCKER_CONTAINER_NAME: flask-app
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        ssh $SSH_USER@$SSH_HOST << 'EOF'
          cd /repositories/CustomerServiceSentinel/backend

          # Build the new Docker image
          docker build -t $DOCKER_IMAGE .

          # Stop the running container
          docker ps -q --filter "ancestor=$DOCKER_IMAGE" | xargs -r docker stop

          # Remove the old container
          docker ps -a -q --filter "ancestor=$DOCKER_IMAGE" | xargs -r docker rm

          # Run the new container
          docker run -d -p 5000:5000 --env-file .env $DOCKER_IMAGE
        EOF
