name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass openssh-client

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add GitHub to known_hosts
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Add SSH Key to Agent
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
        ssh-add key.pem

    - name: Deploy to VM
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      run: |
        sshpass -p $SSH_PASSPHRASE ssh -o StrictHostKeyChecking=no -A $SSH_USER@$SSH_HOST << 'EOF'
          # Ensure sshpass is installed on the VM
          sudo apt-get update && sudo apt-get install -y sshpass

          cd ~/repositories/CustomerServiceSentinel/backend

          # Ensure repository is up-to-date using the correct SSH key
          GIT_SSH_COMMAND="sshpass -p $SSH_PASSPHRASE ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" git pull origin main

          # Build the new Docker image
          docker build -t flask-app .

          # Stop the running container
          docker ps -q --filter "ancestor=flask-app" | xargs -r docker stop

          # Remove the old container
          docker ps -a -q --filter "ancestor=flask-app" | xargs -r docker rm

          # Run the new container
          docker run -d -p 5000:5000 --env-file .env flask-app
        EOF
