name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  pull-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y openssh-client expect

    - name: Set up SSH agent and add key
      env:
        GH_SSH_PASSPHRASE: ${{ secrets.GH_SSH_PASSPHRASE }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GH_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        eval $(ssh-agent -s)
        expect <<- DONE
        spawn ssh-add ~/.ssh/id_ed25519
        expect "Enter passphrase for ~/.ssh/id_ed25519:"
        send "$GH_SSH_PASSPHRASE\r"
        expect eof
        DONE

    - name: Add GitHub to known_hosts
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Pull latest code from GitHub
      run: git pull origin main
