name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  pull-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass and OpenSSH client
      run: sudo apt-get update && sudo apt-get install -y sshpass openssh-client

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add GitHub to known_hosts
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Add SSH Key to Agent
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-add ~/.ssh/id_ed25519

    - name: Pull latest code on VM
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      run: |
        sshpass -p $SSH_PASSPHRASE ssh -o StrictHostKeyChecking=no -A $SSH_USER@$SSH_HOST << 'EOF'
          eval $(ssh-agent -s)
          echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_ed25519
          cd ~/repositories/CustomerServiceSentinel/backend
          GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" git pull origin main
        EOF

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: pull-code

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass and OpenSSH client
      run: sudo apt-get update && sudo apt-get install -y sshpass openssh-client

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add GitHub to known_hosts
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Build and deploy Docker image on VM
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      run: |
        sshpass -p $SSH_PASSPHRASE ssh -o StrictHostKeyChecking=no -A $SSH_USER@$SSH_HOST << 'EOF'
          cd ~/repositories/CustomerServiceSentinel/backend

          # Build the new Docker image
          docker build -t flask-app .

          # Stop the running container
          docker ps -q --filter "ancestor=flask-app" | xargs -r docker stop

          # Remove the old container
          docker ps -a -q --filter "ancestor=flask-app" | xargs -r docker rm

          # Run the new container
          docker run -d -p 5000:5000 --env-file .env flask-app
        EOF
