name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y sshpass openssh-client

    - name: Set up SSH for VM
      env:
        SSH_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: SSH into VM and pull latest code
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        GH_SSH_PRIVATE_KEY: ${{ secrets.GH_SSH_PRIVATE_KEY }}
        GH_SSH_PASSPHRASE: ${{ secrets.GH_SSH_PASSPHRASE }}
      run: |
        sshpass -p ${{ secrets.VM_SSH_PASSPHRASE }} ssh -o StrictHostKeyChecking=no -A $SSH_USER@$SSH_HOST << 'EOF'
          mkdir -p ~/.ssh
          echo "$GH_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519_github
          chmod 600 ~/.ssh/id_ed25519_github
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          expect <<- DONE
          spawn ssh-add ~/.ssh/id_ed25519_github
          expect "Enter passphrase for ~/.ssh/id_ed25519_github:"
          send "$GH_SSH_PASSPHRASE\r"
          git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519_github -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          cd ~/repositories/CustomerServiceSentinel/backend
          git pull origin main
        EOF
