name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add GitHub to known_hosts
      run: ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Add SSH Key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -

    - name: Deploy to VM
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      run: |
        sshpass -p $SSH_PASSPHRASE ssh -o StrictHostKeyChecking=no -A $SSH_USER@$SSH_HOST << 'EOF'
          cd ~/repositories/CustomerServiceSentinel/backend

          # Pull newest commits
          git pull origin main

          # Build the new Docker image
          docker build -t flask-app .

          # Stop the running container
          docker ps -q --filter "ancestor=flask-app" | xargs -r docker stop

          # Remove the old container
          docker ps -a -q --filter "ancestor=flask-app" | xargs -r docker rm

          # Run the new container
          docker run -d -p 5000:5000 --env-file .env flask-app
        EOF
